#######################################################################
#                          ShyBossBar                                 #
# 		            	   by Shynixn							      #
#######################################################################

############################
# Language settings
############################
language: "en_us"

############################
# Command settings
############################
commands:
  shybossbar:
    aliases:
      - "ssbossbar"

############################
# Global BossBar Settings
############################
global:
  # How often are the permissions of a player checked to determine if he has got access to any bossbar.
  checkForChangeSeconds: 3
  # When a new player joins the server, after how many seconds are the bossbars created.
  joinDelaySeconds: 3
